// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccDataSourceFvUplinkOrderContWithFvRsDomAtt(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "4.2(1i)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			{
				Config:             testConfigFvUplinkOrderContDataSourceDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "active", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "description", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "name", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "name_alias", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "owner_key", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("data.aci_uplink_order_container.test", "standby", ""),
				),
			},
			{
				Config:      testConfigFvUplinkOrderContNotExistingFvRsDomAtt,
				ExpectError: regexp.MustCompile("Failed to read aci_uplink_order_container data source"),
			},
		},
	})
}

const testConfigFvUplinkOrderContDataSourceDependencyWithFvRsDomAtt = testConfigFvUplinkOrderContMinDependencyWithFvRsDomAtt + `
data "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  depends_on = [aci_uplink_order_container.test]
}
`

const testConfigFvUplinkOrderContNotExistingFvRsDomAtt = testConfigFvRsDomAttMin + `
data "aci_uplink_order_container" "test_non_existing" {
  parent_dn = aci_relation_to_domain.test.id
}
`
