// Code generated by "gen/generator.go"; DO NOT EDIT.
// In order to regenerate this file execute `go generate` from the repository root.
// More details can be found in the [README](https://github.com/CiscoDevNet/terraform-provider-aci/blob/master/README.md).

package provider

import (
	"regexp"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestAccResourceFvUplinkOrderContWithFvRsDomAtt(t *testing.T) {

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "4.2(1i)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigFvUplinkOrderContMinDependencyWithFvRsDomAttAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "standby", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "standby", ""),
				),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "false")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "4.2(1i)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:      testConfigFvUplinkOrderContMinDependencyWithFvRsDomAttAllowExisting,
				ExpectError: regexp.MustCompile("Object Already Exists"),
			},
		},
	})

	setEnvVariable(t, "ACI_ALLOW_EXISTING_ON_CREATE", "true")
	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "4.2(1i)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigFvUplinkOrderContMinDependencyWithFvRsDomAttAllowExisting,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test", "standby", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.allow_test_2", "standby", ""),
				),
			},
		},
	})

	resource.Test(t, resource.TestCase{
		PreCheck:                 func() { testAccPreCheck(t, "apic", "4.2(1i)-") },
		ProtoV6ProviderFactories: testAccProtoV6ProviderFactories,
		Steps: []resource.TestStep{
			// Create with minimum config and verify default APIC values
			{
				Config:             testConfigFvUplinkOrderContMinDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "standby", ""),
				),
			},
			// Update with all config and verify default APIC values
			{
				Config:             testConfigFvUplinkOrderContAllDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "active", "active_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotation", "annotation"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "description", "description_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name", "name_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name_alias", "name_alias_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_key", "owner_key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_tag", "owner_tag_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "standby", "standby_1"),
				),
			},
			// Update with minimum config and verify config is unchanged
			{
				Config:             testConfigFvUplinkOrderContMinDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check:              resource.ComposeAggregateTestCheckFunc(),
			},
			// Update with empty strings config or default value
			{
				Config:             testConfigFvUplinkOrderContResetDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check:              resource.ComposeAggregateTestCheckFunc(),
			},
			// Import testing
			{
				ResourceName:      "aci_uplink_order_container.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children
			{
				Config:             testConfigFvUplinkOrderContChildrenDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "active", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotation", "orchestrator:terraform"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "description", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "name_alias", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_key", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "owner_tag", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "standby", ""),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.1.value", "test_value"),
				),
			},
			// Refresh State before import testing to ensure that the state is up to date
			{
				RefreshState:       true,
				ExpectNonEmptyPlan: false,
			},
			// Import testing with children
			{
				ResourceName:      "aci_uplink_order_container.test",
				ImportState:       true,
				ImportStateVerify: true,
			},
			// Update with children removed from config
			{
				Config:             testConfigFvUplinkOrderContChildrenRemoveFromConfigDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.#", "2"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.key", "key_0"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.value", "value_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.1.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.1.value", "test_value"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.#", "2"),
				),
			},
			// Update with children first child removed
			{
				Config:             testConfigFvUplinkOrderContChildrenRemoveOneDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.#", "1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.key", "key_1"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.0.value", "test_value"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.#", "1"),
				),
			},
			// Update with all children removed
			{
				Config:             testConfigFvUplinkOrderContChildrenRemoveAllDependencyWithFvRsDomAtt,
				ExpectNonEmptyPlan: false,
				Check: resource.ComposeAggregateTestCheckFunc(
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "annotations.#", "0"),
					resource.TestCheckResourceAttr("aci_uplink_order_container.test", "tags.#", "0"),
				),
			},
		},
		CheckDestroy: testCheckResourceDestroy,
	})
}

const testConfigFvUplinkOrderContMinDependencyWithFvRsDomAttAllowExisting = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "allow_test" {
  parent_dn = aci_relation_to_domain.test.id
}
resource "aci_uplink_order_container" "allow_test_2" {
  parent_dn = aci_relation_to_domain.test.id
  depends_on = [aci_uplink_order_container.allow_test]
}
`

const testConfigFvUplinkOrderContMinDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
}
`

const testConfigFvUplinkOrderContAllDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  active = "active_1"
  annotation = "annotation"
  description = "description_1"
  name = "name_1"
  name_alias = "name_alias_1"
  owner_key = "owner_key_1"
  owner_tag = "owner_tag_1"
  standby = "standby_1"
}
`

const testConfigFvUplinkOrderContResetDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  active = ""
  annotation = "orchestrator:terraform"
  description = ""
  name = ""
  name_alias = ""
  owner_key = ""
  owner_tag = ""
  standby = ""
}
`
const testConfigFvUplinkOrderContChildrenDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  annotations = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
  tags = [
    {
      key = "key_0"
      value = "value_1"
    },
    {
      key = "key_1"
      value = "test_value"
    },
  ]
}
`

const testConfigFvUplinkOrderContChildrenRemoveFromConfigDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
}
`

const testConfigFvUplinkOrderContChildrenRemoveOneDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  annotations = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
  tags = [ 
	{
	  key = "key_1"
	  value = "test_value"
	},
  ]
}
`

const testConfigFvUplinkOrderContChildrenRemoveAllDependencyWithFvRsDomAtt = testConfigFvRsDomAttMin + `
resource "aci_uplink_order_container" "test" {
  parent_dn = aci_relation_to_domain.test.id
  annotations = []
  tags = []
}
`
